image: docker:stable
services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

terraform:
  stage: test
  script:
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t hashicorp/terraform:latest init
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t hashicorp/terraform:latest fmt -check=true
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t hashicorp/terraform:latest validate -check-variables=false

readme-validator:
  stage: test
  script:
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-readme-validator tf_readme_validator.py

cred-alert:
  stage: test
  script:
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:cred-alert cred-alert scan -f .

tflint:
  stage: test
  script:
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t wata727/tflint --error-with-issues

terrascan:
  stage: test
  script:
    - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t tmknom/terrascan --location . --test all
