dist: xenial
sudo: required

services:
  - docker

before_script:
  - echo 'before_script'
  - git clone https://github.com/kamatama41/tfenv.git ~/.tfenv
  - sudo ln -s ~/.tfenv/bin/* /usr/local/bin
  - tfenv install latest:^0.11
  - terraform -v
  - echo 'check credentials'
  - os_name=$(uname | awk '{print tolower($1)}')
  - curl -o cred-alert https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_${os_name}
  - chmod 755 cred-alert
  - ./cred-alert scan -f .

script:
  - echo 'script'
  - terraform init --input=false
  - terraform fmt -check=true -list=true
  - terraform validate -check-variables=false
  # We provide Docker images for each version on DockerHub. With docker, you can run TFLint without installing it locally
  # https://github.com/wata727/tflint
  - docker run --rm -v $(pwd):/app/ --workdir=/app/ -t wata727/tflint --error-with-issues
  # Collection of security and best practice test for static code analysis of terraform templates.
  # This is terrascan wrapper.
  # https://github.com/tmknom/terrascan
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t tmknom/terrascan --location . --test all
  #- cd examples/some_tests
  #- terraform init
  #- terraform fmt -check=true
  #- terraform validate
  #- cd -
  - terraform -v
