dist: xenial
sudo: required

services:
  - docker

before_script:
  - echo 'Installing tfenv'
  - git clone https://github.com/kamatama41/tfenv.git
  - PATH=$PATH:$(pwd)/tfenv/bin
  - echo 'Installing terraform'
  - tfenv install latest:^0.11
  - terraform -v
  - echo 'Installing cred-alert'
  - os_name=$(uname | awk '{print tolower($1)}')
  - curl -o cred-alert https://s3.amazonaws.com/cred-alert/cli/current-release/cred-alert-cli_${os_name}
  - chmod 755 cred-alert
  - echo 'Running cred-alert'
  - ./cred-alert scan -f .

script:
  - echo 'Running terraform init'
  - terraform init
  - echo 'Running terraform fmt'
  - terraform fmt -check=true
  - echo 'Running terraform validate'
  - terraform validate
  - echo 'Running tfling'
  - docker run --rm -v $(pwd):/app/ --workdir=/app/ -t wata727/tflint --error-with-issues
  - echo 'Running terrascan'
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t tmknom/terrascan --location . --test all
